### ISSUE TITLE
1.3 object-ID bronhouder

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#10]
Blz. 47.

Er is behoefte aan extra attributen voor naamgeving en identificatie conform de discussie bij de Grondwatermonitoringput.
Bij registratieobject grondwatermonitoringput heeft uitgebreide discussie plaats gevonden over de behoefte aan mogelijkheden voor: historische naam, gebruikersnamen, en unieke naamgeving voor nieuwe putten. Voor Booronderzoek zijn dezelfde argumenten aan de orde en dit moet consistent worden doorgevoerd conform Grondwatermonitorinput. Er ligt voor grondwatermonitoringsput een consensus voorstel vanuit de gebruikers. Het voorstel is nu om dit voor het Booronderzoek identiek vorm te geven. Het concept voorstel is bijgevoegd.
Concreet is het voorstel:
-toevoegen van historische ID;
-het object ID bronhouder wijzigen in optineel met kardinaliteit 0-2;
-toevoegen van Naam boring; verplicht, kardinaliteit 1, op basis van onder andere kaartblad met nummer conform grondwatermonitoringput.

De discussie loopt nog en het voorstel is om de invulling omtrent dit issue consistent te laten zijn met grondwatermonitoringput.

[20170124 - Voorstel BRO-ID - versie 0 94.docx](https://github.com/BROprogramma/booronderzoek/files/783142/20170124.-.Voorstel.BRO-ID.-.versie.0.94.docx)

**Comment by MarcelReuvers** [comment]
Dit voorstel tot wijziging heeft een behoorlijke impact en is nog niet door anderen opgevoerd. We zullen straks op basis van het gebruik gaan monitoren wat aanvullende behoeften zijn. Dit kan betekenen, zodra meerdere partijen hiermee komen, dat bovenstaande wijzigingen in een volgende versie erbij kunnen komen.
