### ISSUE TITLE
StandaardGrondsoortnaam

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#11]
blz 158.

De tabel gebaseerd op NEN 5104, terwijl deze norm is vervallen. Formeel en wettelijk nog niet vervangen door NEN-en-ISO 14688, maar wellicht wel zinvol om hier al op voor te sorteren want het is zeker te verwachten dat laatst genoemde norm toegepast zal worden.

**Comment by MarcelReuvers** [comment]
Zie 19.1, is al opgenomen

**Comment by harryvanmanen** [comment]
Hallo Marcel,

Waar gaat dit over? Deze verwijzing snap ik niet.

Met vriendelijke groet,
Harry van Manen

Van: MarcelReuvers [mailto:notifications@github.com]
Verzonden: dinsdag 20 juni 2017 8:55
Aan: BROprogramma/booronderzoek
CC: Manen, Harry van (WVL); Author
Onderwerp: Re: [BROprogramma/booronderzoek] StandaardGrondsoortnaam (#11)


Zie 19.1, is al opgenomen
