### ISSUE TITLE
Reikwijdte catalogus Bodemkundige boormonsterbeschrijving

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/booronderzoek#12]
Graag de reikwijdte duidelijker positioneren. 

Na de hieronder gegeven redenering kom ik tot de conclusie dat de catalogus Bodemkundige boormonsterbeschrijving van toepassing op booronderzoek waarvoor de beschrijfmethode AlterraTD19A geldt. Zo'n redenering moet overbodig zijn. Het zou ook helpen wanneer wordt aangegeven in welke situaties betreffend booronderzoek/bodemkundige boorbeschrijving aan de orde kan zijn. In dit geval bijvoorbeeld (ter verfijning van) de Bodemkaart.

Redeneerlijn leidend tot de conclusie:
-	In ieder geval niet voor onderzoek dat er op is gericht de kwaliteit van de bodem vanuit milieukundig onderzoek te bepalen (zie blz 20 en blz 45 – populatie registratieobject).

-	De catalogus dekt de gegevensdefinitie voor het vakgebied bodemkunde en daarbinnen nog alleen het deelonderzoek waarin de bodemmonsters beschreven worden om een bodemprofiel te maken (à la Bodemkaart) blz 21/22. De standaard die gebruikt wordt voor de beschrijving van de bodemprofielen is de ‘Handleiding bodemgeografisch onderzoek, richtlijnen en voorschriften’, Technisch document 19A, 1995 gebruikt, blz 26. Op blz 114 wordt dit TD ook genoemd onder Beschrijfmethode. De verwijzing daarnaar – codelijst – vindt plaats op blz 77. De beschrijfmethode geeft aan volgens welk stelsel van afspraken de monsters beschreven zijn en welke aspecten worden beschreven. Kardinaliteit , dit betekent dat het gegeven altijd aanwezig is en altijd een waarde moet hebben. In de codelijst, blz 114, staat één waarde voor de beschrijfmethode: AlterraTD19A.

Voor de liefhebber: http://maps.bodemdata.nl/bodemdatanl/index.jsp Via deze link kun achterhalen wat het resultaat is van een bodemkundige boormonsterbeschrijving.

**Comment by MarcelReuvers** [comment]
De opmerkingen zijn verwerkt in de nieuwe paragraaf 1.2
