### ISSUE TITLE
pragraaf 3.3

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/booronderzoek#18]
Locatie: pagina 21 van 172

zinsnede: Deze versie van de catalogus voor booronderzoek dekt alleen de gegevensdefinitie voor het vakgebied bodemkunde en daarbinnen nog alleen het deelonderzoek waarin de boormonsters beschreven worden om een bodemprofiel te maken (figuur 4).

Opmerking: Voor het duidelijke leesdoel van dit document, deze alinea opnemen in de inleiding.

**Comment by MarcelReuvers** [comment]
Er is een paragraaf 1.2 ingevoegd om al in de inleiding aan te  geven dat de scope van deze versie zich beperkt tot de bodemkundige boormonsterbeschrijving.
