### ISSUE TITLE
Hoofdstuk 2 Algemene kenmerken en begrippen

### ISSUE THREAD

**Issue by keestjaden** [BROprogramma/booronderzoek#2]
Dit hoofdstuk staat in alle tot nu toe gepubliceerde catalogi. Het lijkt me handiger hier een apart document van te maken, omdat er nu verschillen zijn in de tekst tussen de catalogi.
Voorbeeld 1: pag. 14 2de en 3de alinea: waarschijnlijk wordt hetzelfde bedoeld, maar de teksten zijn niet gelijk.
voorbeeld 2: in de vorige catalogi staat paragraaf 2.9 op een andere plek, nl paragraaf 2.6

**Comment by MarcelReuvers** [comment]
We houden de catalogi onderling consistent. 
Mogelijk dat we later dezelfde teksten in een apart document gaan zetten.
