### ISSUE TITLE
Afstemming met eerdere beoordelingen op vegelijkbare onderdelen

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/booronderzoek#21]
Binnen de catalogus zijn, onder hoofdstuk 4 en verder, een groot aantal vergelijkbare onderdelenen invoervelden omschreven als met voorgaande beoordeelde catalogussen. Mag aangenomen worden dat gemaakte opmerkingen in dit geval generiek worden aangepast c.q. beantwoord? E.e.a. zoals het ook generiek is toegepast bij het opstellen van de catalogussen.

Uitgaan wordt da dit van toepassing is. Er zijn dan ook geen verdere issues ingevoerd in dit systeem.

**Comment by MarcelReuvers** [comment]
We houden de catalogi onderling consistent.
