### ISSUE TITLE
Domeinlijsten

### ISSUE THREAD

**Issue by FolkertdeVries** [BROprogramma/booronderzoek#22]
## Opmerking bij domeinlijst AFZETTINGSKARAKTERISTIEK
In de domeinlijst Afzettingskarakteristiek ontbreekt een deel van de omschrijving bij "fluviatielUiterwaardHoloceen". Ik stel voor om "Afzetting van Rijn of Maas" aan het begin van de omschrijving toe te voegen.

**Comment by FolkertdeVries** [comment]
## Opmerking bij domeinlijst BODEMKUNDIGEGRONDSOORTNAAM
Het is verplicht om voor elk laagcomponent de BodemKundigeGrondsoortnaam aan te geven. Voor een laag die uit meer dan 30% schelpen bestaat is geen grondsoortnaam beschikbaar. Het is ook niet mogelijk om 'nietBepaald' of 'onbekend' aan te geven want die waarden komen niet in de domeinlijst voor. 
Voorstel: voeg grondsoort 'schelpmateriaal' toe (conform standaardGrondsoortnaam). En voeg 'nietBepaald' toe

**Comment by MarcelReuvers** [comment]
afzettingskarakteristiek: aangepast
bodemkundige grondsoortnaam: aangepast
