### ISSUE TITLE
Regels voor het al dan niet aanwezig zijn van attribuutwaarden

### ISSUE THREAD

**Issue by FolkertdeVries** [BROprogramma/booronderzoek#23]
## Regel voor zandmediaan
Volgens de catalogus mag voor een laagcomponent de zandmediaan alleen worden gegeven wanneer de _bodemkundigegrondsoortnaam_ eindigt op _zand_ en niet gelijk is aan _venigZand_. Voor laagcomponenten met meer dan 8% lutum kan informatie over de zandmediaan echter heel waardevol zijn. Een kenmerk van keileem bijvoorbeeld is dat de zandfractie matig fijn tot matig grof is. Bij rivierklei komt afhankelijk van de ligging ook verschil in grofheid van de zandfractie voor. Bij bodemkundige boorbeschrijvingen wordt dit vastgelegd. 
**Voorstel voor wijziging van de regel:**  Het gegeven is aanwezig wanneer de waarde van de bodemkundige grondsoortnaam eindigt op _Zand_ en niet gelijk is aan _venigZand_. Bij andere grondsoorten is het gegeven toegestaan maar niet verplicht.

**Comment by yke** [comment]
Geef even duidelijk aan dat je met "het gegeven is aanwezig" bedoeld dat "het gegeven aanwezig is en een waarde heeft"

**Comment by MarcelReuvers** [comment]
Dit is verwerkt.

**Comment by yke** [comment]
geef even aan of het gehonoreerd is of niet uitgewerkt wordt.
