### ISSUE TITLE
Inname van getalswaarden

### ISSUE THREAD

**Issue by FolkertdeVries** [BROprogramma/booronderzoek#24]
Op pagina 41 van de catalogus worden de praktische regels beschreven die de basisregistratie hanteert bij de inname van getalswaarden. 
Bij het aanleveren van gegevens door Alterra blijkt dat de regels niet worden toegepast. Bijvoorbeeld wanneer er meer decimalen worden aangeleverd dan toegestaan, dan worden deze "**niet afgekapt**", zoals in de catalogus is aangegeven.
Ook zijn er problemen met het aanleveren van natuurlijke getallen

**Comment by MarcelReuvers** [comment]
De software wordt aangepast op de vereisten van de catalogus. De catalogus wordt hier dus niet op aangepast.
