### ISSUE TITLE
Volledigheid van de Boormonsterbeschrijving

### ISSUE THREAD

**Issue by FolkertdeVries** [BROprogramma/booronderzoek#25]
## Fractieverdeling bepaald

In entiteit boormonsterbeschrijving is het attribuut "fractieverdeling bepaald (ja/nee)" opgenomen. Bij de gegevens van de laagcomponenten bepaald dit attribuut of entiteit fractieverdeling wordt aangeleverd of niet. In de praktijk is de volledigheid van de laagbeschrijving gerelateerd aan de grondsoort. Bij klei wordt vaak geen zand geschat en bij veen ontbreekt het lutum- en of siltgehalte vaak. Er zijn veel boorbeschrijving waarbij voor slechts 1 laagcomponent de fractieverdeling niet compleet is. 
**Opmerking:** zou het daarom niet beter zijn het attribuut "fractieverdeling bepaald" te verplaatsen naar bodemlaag of laagcomponent??

**Comment by MarcelReuvers** [comment]
Dit is verwerkt.

**Comment by yke** [comment]
Ik zie dat het verwerkt is maar is het gehonoreerd of wordt deze aanpassing niet uitgevoerd.
