### ISSUE TITLE
Consistentie algemene inhoud Registratieobjecten 

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#3]
De inhoud van de algemene hoofdstukken van de verschillende registratieobjecten moet consistent zijn. Bijvoorbeeld: bij het registratieobject grondwatermonitoringput zijn opmerkingen gemaakt en doorgevoerd die betrekking hebben op algemene onderwerpen. Wordt hier rekening mee gehouden zodat alle catalogussen voor het algemene deel gelijk zijn er geen tegenstrijdigheden aan de orde zijn?
Ik neem algemene opmerkingen van andere registratieobjecten niet nogmaals op in de catalogus Booronderzoek.

**Comment by MarcelReuvers** [comment]
we houden de catalogi consistent
