### ISSUE TITLE
Inlijn brengen met booronderzoek tranche 2 & 3

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/booronderzoek#31]

**Comment by Naj6jep** [comment]
Waar: [Aanduiding van de plek in de catalogus, bijvoorbeeld Paragraaf x.x, pagina x en verder]
Samenvatting: [uitleg van het probleem]
Beschrijving: [uitgebreidere beschrijving van het probleem, argumentatie]
Oplossingsrichting: [zo concreet mogelijk voorstel voor aanvulling/verbetering/wijziging]
**Verwijderd:**
Van de entiteit Booronderzoek zijn attributen boorgat bemeten, boormonstersbeschreven, boormonsters geanalyseerd, boormonstersgefotografeerd verwijderd.
**Hernoemd**
Het attribuut strooisellaag beschreven is hernoemt naar "strooissellaag onderzocht".

**Domein aangepast**
Van alle attributen met het domein "KvK-nummer" is het domein gewijzigd in "Organisatie".
Het gaat om: bronhouder, dataleverancier, uitvoerder onderzoek van de entiteit Booronderzoek.
uitvoerder boring van de entiteit Boring
uitvoerder beschrijving van de entiteit Boormonsterbeschrijving
uitvoerder locatiebepaling van de entiteit Aangeleverde locatie
uitvoerder verticale positiebepaling van de entiteit Aangeleverde verticale positie

**Toegevoegd:**
Entiteit Rapportagegeschiedenis met de attributen startdatum rapportage en einddatum rapportage
Entiteit Tussentijdse gebeurtenis met de attributen naam gebeurtenis en datum gebeurtenis
