### ISSUE TITLE
Acceptatieomgeving bronhouderportaal ondersteunt geen correcteis voor BHR-P

### ISSUE THREAD

**Issue by yke** [BROprogramma/booronderzoek#33]
Tijdens het aanpassen van onze applicatie om BHR-P registratieobjecten te leveren aan BRO kwam ik erachter dat correcties (nog) niet worden ondersteunt.

De foutmelding

```json
{
    "identifier": "0000007133",
    "status": "AANGELEVERD",
    "lastChanged": "2019-11-05T12:56:58.008",
    "brondocuments": [{
            "id": 21758,
            "status": "ONGELDIG",
            "lastChanged": "2019-11-05T12:56:58.008",
            "filename": "ceee35d9f2ca.xml",
            "errors": ["Bestand ceee35d9f2ca.xml zou een IMBRO XML bestand moeten zijn."]
        }
    ]
}
```
Ik heb het XML bestand (conform het BHR-P transactiemodel) gezipped bijgevoegd.

[correctie-bpk-149226.zip](https://github.com/BROprogramma/BHR-P/files/3813067/correctie-bpk-149226.zip)

**Comment by BartJandeLeuw** [comment]
Dit gemelde issue is opgepakt door de BRO ketenteams. De keten was nog niet geconfigureerd voor correcties op BHR-P.

**Comment by RuudMutsaers** [comment]
Corecties zijn inmiddels geimplementeerd in de LV

**Comment by BartJandeLeuw** [comment]
Leuk van je te horen, BRO
