### ISSUE TITLE
Moerigmateriaal

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/booronderzoek#34]
zie https://github.com/BROprogramma/SFR/issues/37
dit SFR issue speelt ookin BHR-P

**Comment by fterpstra** [comment]
issue speelt nog in 1.9 versie catalogus zal worden meegenomen met verwerking publieke consultatie in versie 1.99 versie catalogus

**Comment by fterpstra** [comment]
Deze is uiteindelijk niet meegenomen in de 1.99 versie.  In de beheerfase kunnen we hier nogmaals naar kijken mogelijk in de bredere context van een harmonisatie over vakgebieden heen.

**Comment by BregjeBrugman** [comment]
opgenomen in werkafspraak tranche 3 (nr. 4)
