### ISSUE TITLE
Issues bij SFR-P gelden ook voor BHR-P

### ISSUE THREAD

**Issue by yke** [BROprogramma/booronderzoek#36]
## Type issue
Publieke consultatie

## Waar
Diverse plekken in catalogus

## Beschrijving
[Lange omschrijving van de melding. Probeer zo concreet mogelijk het probleem of je suggestie voor verbetering te beschrijven. Bijvoorbeeld: 'Het is onduidelijk wat er precies met ... bedoeld wordt'.]

## Oplossingsrichting
Meer en betere harmonisatie, aanpassen proces zodat harmonisatie een uitgangspunt is en geen actie achteraf.

**Comment by fterpstra** [comment]
In de   beheerfase wordt de harmonisatie tussen SFR en BHR-P opgepakt. Net zoals de   harmonasatie binnen booronderzoek voor de beheerfase is gepland. We erkennen   dat harmonsatie zeer wenselijk is. De afweging om deze nu niet mee te nemen   is gedaan in overleg met de Keten BRO. Men had binnen de planning voor de   realisatie van tranche 3 niet de ruimte om ook een geharmoniseerde BHR-P te   bouwen.
--
zie ook https://basisregistratieondergrond.nl/publish/library/265/terugkoppeling_publieke_consultatie_bhr-p_en_sfr.xlsx voor beantwoording.

**Comment by BregjeBrugman** [comment]
issues die zijn gemeld bij SFR en ook van toepassing zijn voor BHR-P, zijn voor beide catalogi opgepakt.
