### ISSUE TITLE
Open punt vanuit het standaardisatie team

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#37]
## Type issue

Foutherstel

## Waar

attribuut   verschuiving

## Samenvatting

regel   verbeteren

## Beschrijving

Check de   regel voor niet-gespecificeerde waardebereik.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
