### ISSUE TITLE
corrigeren bereik attributen entiteit Verwerkingsstap

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#38]
## Type issue
Foutherstel

## Waar
attribuut   3.61.3	kleinste gemeten bodemvochtpotentiaal en grootste gemeten   bodemvochtpotentiaal van de entiteit Verwerkingsstap

## Samenvatting
corrigeren   bereik

## Beschrijving
Het   domein is niet compleet.

## Oplossingsrichting
Aanpassen   in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
