### ISSUE TITLE
Entiteit Modellering waterretentiekarakteristiek verbeteren

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#39]
## Type issue
Foutherstel

## Waar
Entiteit Modellering waterretentiekarakteristiek

## Samenvatting
entiteit   verbeteren

## Beschrijving
De regel klopt niet.

## Oplossingsrichting
De definitie en toelichting tekstueel verbeteren.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
