### ISSUE TITLE
Kwaliteitborging van Beoordelingsrichtlijnen en Normen

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#4]
Voor het registratieobject grondwatermonitoringput wordt voor  het inrichten en plaatsen veelal beoordelingsrichtlijn 2001 (BRL 2001) en NEN 5104 (wordt vervangen door NEN-en-ISO 14688) gebruikt. Daarin zijn eisen gesteld aan booronderzoek en boormonsterbeschrijving. Kan in deze catalogus een en ander worden afgestemd op de richtlijnen en normen zodat het naadloos op elkaar aansluit. 
Ofwel, er moeten gegevens kunnen worden aangeboden die voldoen aan de BRL 2001 en NEN 5104 (of 14688).
Bijkomende vraag is of deze catalogus is gebaseerd (of in lijn is met) op NEN 5104/NEN-en-ISO 14688?

**Comment by MarcelReuvers** [comment]
De ISO 14688 wordt momenteel opgepakt als onderdeel van tranche 2. We zullen ook bekijken wat dit betekent voor de huidige bodemkundige boormonsterbeschrijving. 
Het oppakken van ISO 14688 kon ook niet eerder omdat de NEN normcommissie geotechniek pas gereed is met de nederlandse aanpak op ISO 14688. Deze nederlandse aanpak moet overigens nog geconsulteerd worden in Nederland maar dit loopt parallel met onze tranche 2.
