### ISSUE TITLE
verwijderen  entiteit Wandfotografie

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#40]
## Type issue
Foutherstel

## Waar
Wandfotografie  BUITEN SCOPE

## Samenvatting
verwijderen  entiteit Wandfotografie

## Beschrijving
De  gegevens over de wandfotografie niet opnemen in de gegevensdefinitie omdat   het buiten scope is.

## Oplossingsrichting
Verwijderen   uit de gegevensdefinitie

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
