### ISSUE TITLE
kardinaliteit verbeteren attribuut droogtijd van de entiteit Bepaling waterretentie stapsgewijs

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#41]
## Type issue
Foutherstel

## Waar
attribuut droogtijd van de entiteit Bepaling waterretentie stapsgewijs

## Samenvatting
kardinaliteit   verbeteren

## Beschrijving
De   kardinaliteit staat verkeerd en moet aangepast worden naar 1. Gaat dit goed   voor archiefgegevens? en de toelichting tekstueel checken

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
