### ISSUE TITLE
corrigeren bereik attribuut vormfactor lambda van de entiteit Modelleringsstap

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#42]
## Type issue
Foutherstel

## Waar
attribuut   vormfactor lambda van de entiteit Modelleringsstap

## Samenvatting
corrigeren  bereik

## Beschrijving
Het   domein is niet compleet.

## Oplossingsrichting
Afspraken   maken met de experts van WEnR

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
