### ISSUE TITLE
corrigeren bereik attribuut rapportagegrens van de entiteit Bepaling Organischekoolstofgehalte

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#43]
## Type issue
Foutherstel

## Waar
attribuut   rapportagegrens van de entiteit Bepaling Organischekoolstofgehalte

## Samenvatting
corrigeren bereik

## Beschrijving
De   opbouw en waardebereik komen niet overeen.

## Oplossingsrichting
Open

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
