### ISSUE TITLE
attribuut horizontcode van de entiteit Onderzocht interval

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#45]
## Type issue
Foutherstel

## Waar
attribuut   horizontcode van de entiteit Onderzocht interval

## Samenvatting
regel   verbeteren

## Beschrijving
De regel   klopt niet

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
