### ISSUE TITLE
Sturing van de bepalingen binnen het Onderzocht Interval met soort analyses

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#46]
## Type issue
Foutherstel

## Waar
Sturing van de bepalingen binnen het Onderzocht Interval met soort analyses

## Samenvatting
regel   verbeteren

## Beschrijving
De   regels en de sturing nalopen en verbeteren.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
