### ISSUE TITLE
attribuut lutumcorrectie toegepast van de entiteit Bepaling organischestofgehalte

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#47]
## Type issue
Foutherstel

## Waar
attribuut lutumcorrectie toegepast van de entiteit Bepaling organischestofgehalte

## Samenvatting
regel verbeteren

## Beschrijving
De  regels kloppend maken.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
