### ISSUE TITLE
Open punt vanuit het standaardisatie team

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#48]
## Type issue

Foutherstel

## Waar

Modellering   bodemvochtpotentiaal, watergehalte en waterdoorlatendheid

## Samenvatting

sturing   verbeteren

## Beschrijving

De   sturing op de entiteit Modellering bodemvochtpotentiaal,   watergehalte en waterdoorlatendheid is niet   correct.

## Oplossingsrichting

Aanpassen   in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
