### ISSUE TITLE
waarde schuifmaat (z+x) uit Bepalingsmethode verwijderen

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#49]
## Type issue
Foutherstel

## Waar
Waardelijst Bepalingsmethode - waarde schuifmaat (z+x)

## Samenvatting
waarde uit Bepalingsmethode verwijderen

## Beschrijving
De   waarde schuifmaat (z+x) is oud. Deze moet verwijderd worden.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
