### ISSUE TITLE
1.4 Versiehistorie

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#5]
Er wordt beschreven dat deze catalogus alleen bodemkundige boormonsterbeschrijving bevat. Hier direct toelichten wanneer, wat en hoe de andere aspecten behandeld worden.

**Comment by dhvenema** [comment]
Het is ook mogelijk om de versiehistorie in de "Status van dit document" sectie te verwerken, zoals gedaan in: [Nederlands metadataprofiel op ISO-19115](https://geonovum.github.io/Metadata-ISO19115/#sotd).
