### ISSUE TITLE
Waardelijst   VerwijderdMateriaal

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#50]
## Type issue
Foutherstel

## Waar
Waardelijst   VerwijderdMateriaal

## Samenvatting
verwijderen   attribuut verwijderd materiaal van de entiteit organischestofgehalteklasse

## Beschrijving
Deze   waardelijst is onterecht in de gegevensdefinitie opgenomen

## Oplossingsrichting
Verwijderen   uit de gegevensdefinitie

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
