### ISSUE TITLE
attribuut bijzonderheid uitvoering  van de entiteit Bepaling organischestofgehalteklasse

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#51]
## Type issue
Foutherstel team standaardisatie

## Waar
attribuut   bijzonderheid uitvoering  van de   entiteit Bepaling organischestofgehalteklasse

## Samenvatting
verwijderen   attribuut verwijderd materiaal vande entiteit organischestofgehalteklasse

## Beschrijving
Dit   attribuut is onterecht in de gegevensdefinitie opgenomen

## Oplossingsrichting
Verwijderen   uit de gegevensdefinitie

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
