### ISSUE TITLE
verwijderen attribuut verwijderd materiaal van de entiteit organischestofgehalteklasse

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#52]
## Type issue
Foutherstel team standaardisatie

## Waar
attribuut  verwijderd materiaal van de entiteit organischestofgehalteklasse

## Samenvatting
verwijderen attribuut verwijderd materiaal vande entiteit organischestofgehalteklasse

## Beschrijving
Dit   attribuut is onterecht in de gegevensdefinitie opgenomen. Controleren of het ergens goed is omschreven.

## Oplossingsrichting
Verwijderen  uit de gegevensdefinitie

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
