### ISSUE TITLE
verbeteren meetwaarde attribuut pH

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#53]
## Type issue
Foutherstel, team standaardisatie

## Waar
attribuut pH bij entiteit Zuurgraad strooisellaag en zuurgraad bodemlaag

## Samenvatting
verbeteren  meetwaarde

## Beschrijving
Er is   afgesproken dat de meetwaarde 1.1 is ipv 1.2.

## Oplossingsrichting
Aanpassen   in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
