### ISSUE TITLE
verbeteren attribuut uitvoerder analyse

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#54]
## Type issue
Foutherstel team standaardisatie

## Waar
attribuut   uitvoerder analyse

## Samenvatting
verbeteren   attribuut uitvoerder analyse

## Beschrijving
Gegevens   uitvoerder analyse ontbreken.

## Oplossingsrichting
Definitie,   regels en toelichting aanvullen in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
