### ISSUE TITLE
Nummering entiteiten

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#55]
## Type issue

Foutherstel

## Waar

Nummering   entiteiten

## Samenvatting

nummering   corrigeren

## Beschrijving

De   nummers van de entiteiten komen niet overeen met de nummers in het   domeinmodel.

## Oplossingsrichting

De   nummering nalopen en eventueel herstellen in het domeinmodel en/of de   gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
