### ISSUE TITLE
verbeteren domein tekst

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#56]
## Type issue

Foutherstel

## Waar

Domein   tekst wordt niet goed weergegeven.

## Samenvatting

verbeteren   domein

## Beschrijving

Het   domein van de attributen standaardpuntencode en object-ID bronhouder klopt   niet

## Oplossingsrichting

Aanpassen   in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
