### ISSUE TITLE
corrigeren bereik attribuut ringdiameter

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#57]
## Type issue

Foutherstel

## Waar

attribuut   ringdiameter van de entiteit Bepaling waterretentie stapsgewijs

## Samenvatting

corrigeren   bereik

## Beschrijving

Het   waardebereik is onjuist.

## Oplossingsrichting

Aanpassen   in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
