### ISSUE TITLE
verbeteren kardinaliteit attribuut uitvoerder analyse

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#58]
## Type issue

Foutherstel

## Waar

attribuut uitvoerder analyse

## Samenvatting

verbeteren kardinaliteit

## Beschrijving

Kardinaliteit   is verkeerd, moet worden gewijzigd naar 0..1

## Oplossingsrichting

Aanpassen   in de gegevensdefinitie.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
