### ISSUE TITLE
naamswijziging attribuut vormfactor alpha

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#59]
## Type issue

Foutherstel

## Waar

attribuut   vormfactor alpha

## Samenvatting

naamswijziging

## Beschrijving

Naamswijziging   van het attribuut vormfactor alpha naar "vormfactor alfa".

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
