### ISSUE TITLE
2.1 opzet van het systeem

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#6]
_het is de bedoeling dat de registerbeheerder die gegevens niet verandert_. 
Dat is vaag en niet SMART. Voorstel: de registerbeheerder zal de gegevens niet veranderen.

**Comment by MarcelReuvers** [comment]
Tekst gewijzigd: De aangeleverde gegevens vallen onder de verantwoordelijkheid van de bronhouder en de registerbeheerder mag die gegevens niet veranderen.
