### ISSUE TITLE
Verbeteren schrijfwijze Waardelijst Bepalingsmethode

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#60]
## Type issue

Foutherstel

## Waar

Waardelijst Bepalingsmethode - aantalID1 en aantalID2 en aantallDonbekend

## Samenvatting

verbeteren schrijfwijze

## Beschrijving

Spelfout   in de waardes aantallD1 en aantallD2. Dit moet worden aantalD1 en aantalD2 en   aantal1DOnbekend.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
