### ISSUE TITLE
Verbeteren visualisaties plaatjes bij entiteiten

### ISSUE THREAD

**Issue by joerivanes** [BROprogramma/booronderzoek#61]
## Type issue

Foutherstel

## Waar

Plaatjes bij entiteiten

## Samenvatting

verbeteren   visualisaties

## Beschrijving

Visualisatie   bij iedere entiteit uniformiseren.

**Comment by fterpstra** [comment]
opgelost in tranche 3 catalogus zie https://basisregistratieondergrond.nl/publish/library/265/catalogus_bodemkundig_booronderzoek_v0_99_docx.pdf
