### ISSUE TITLE
DSBHR kensets validatie response: boringToolDiameter

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#63]
## Type issue
XSD / regels leiden tot niet consistente XSD.

## Waar
BHR-P 1.1

## Samenvatting
Validatie van de DSBHR response op dispatchCharacteristicsRequest geeft de melding:

line 45: Expected element 'boringToolDiameter@http://www.broservices.nl/xsd/bhrcommon/1.1' before the end of the content  in element boringToolType@http://www.broservices.nl/xsd/dsbhr/1.1

Dit gegeven is niet gespecificeerd als onderdeel van de kenset, en wordt ook niet uitgeleverd.

## Oplossingsrichting
pas de XSD aan (dsbhrp-messages.xsd)
 Zie [hier ](https://jira.gdnnet.nl/browse/BRO-452) voor meer info

**Comment by HanWelmer** [comment]
Ik vermoed dat hier sprake is van een naamsverwarring tussen 

- Het elementnaam boringToolType van het type bhrcom:BoringToolType binnen een BoringToolTypeOverview.

- Het element boringToolType van het type bhrcom:BoringToolTypeType binnen een BoringToolType.

Hoe dan ook, een valide boortypeoverzicht binnen een kenset is bijvoorbeeld (zie de voorbeeldberichten in GitHub) :

      <boringToolTypeOverview>
        <boringToolType>
          <bhrcommon:boringToolType codeSpace="urn:bro:bhr:BoringToolType">edelmanboor</bhrcommon:boringToolType>
          <bhrcommon:boringToolDiameter uom="mm">85</bhrcommon:boringToolDiameter>
          <bhrcommon:boredInterval>
            <bhrcommon:beginDepth uom="m">0.80</bhrcommon:beginDepth>
            <bhrcommon:endDepth uom="m">1.20</bhrcommon:endDepth>
          </bhrcommon:boredInterval>
        </boringToolType>
        <boringToolType>
          <bhrcommon:boringToolType codeSpace="urn:bro:bhr:BoringToolType">guts</bhrcommon:boringToolType>
          <bhrcommon:boringToolDiameter uom="mm">40</bhrcommon:boringToolDiameter>
          <bhrcommon:boredInterval>
            <bhrcommon:beginDepth uom="m">1.20</bhrcommon:beginDepth>
            <bhrcommon:endDepth uom="m">3.70</bhrcommon:endDepth>
          </bhrcommon:boredInterval>
        </boringToolType>
      </boringToolTypeOverview>

**Comment by HanWelmer** [comment]
Volgens de BHR-P Berichtencatalogus uitgiftewebservice moet het overzicht boortypes bestaan uit een lijst van boortypes:
![image](https://user-images.githubusercontent.com/45099757/139068241-1085b4f1-da8d-4ddd-98c0-a61fcf63f18f.png)

In de eerste versie van de XSD voor de uitgifte (tijdens tranche 1 handmatig opgesteld) is hierbij een fout gemaakt:
    element name="boringToolType" type="bhrcom:BoringToolType"

In plaats van:
    element name="boringToolType" type="bhrcom:BoringToolTypeType"

Bij de foute versie van het XSD-bestand bevat de kengegevens het uitgebreide boringToolType zoals aangegeven in het commentaar van 11 maart 2020. In de juiste (huidige) versie van het XSD-bestand bestaat de boringToolType uit:

      <boringToolTypeOverview>
	    <boringToolType codeSpace="urn:bro:bhr:BoringToolType">edelmanboor</boringToolType>
		<boringToolType codeSpace="urn:bro:bhr:BoringToolType">guts</boringToolType>
	  </boringToolTypeOverview>

Het XSD-bestand voor de uitgifte is al correct.
Het voorbeeldbericht in de publieke GitHub is al correct.
Het voorbeeldbericht DC_ResponseLevering.xml in de GitHub van het LV-BRO bouwteam is aangepast.
