### ISSUE TITLE
Attribuut grondsoort staat onterecht binnen laagcomponent in domeinmodel

### ISSUE THREAD

**Issue by fterpstra** [BROprogramma/booronderzoek#64]
## Type issue
ontdekt tijdens realisatie

## Waar
Paragraaf 1.2: bij het figuur Domeinmodel bodemkundig booronderzoek- Boormonsterbeschrijving. Bij blokje 22. (in ministeriële regeling)
Paragraaf 5.2: bij het figuur Domeinmodel bodemkundig booronderzoek- Boormonsterbeschrijving. Bij blokje 22. (in respec versie)

## Samenvatting
In het domeinmodel is dit attribuut vergeten te hiden, want binnen laagcomponent is het attribuut grondsoort van het stereotype gegevensgroep. In alle overige figuren en de teksten staat het wel goed.

## Oplossingsrichting
Aanpassen in UML bij volgende versie catalogus. DWZ dit attribuut hiden in het domeinmodel.

**Comment by BregjeBrugman** [comment]
komt te vervallen bij nieuwe presentatie
