### ISSUE TITLE
BHR-P heeft in catalogus een element wandmonsteranalyse

### ISSUE THREAD

**Issue by yke** [BROprogramma/booronderzoek#65]
## Type issue
Review sessie

## Waar
Pagina 11 in de figuur staat een wandmonsteranalyse gemodelleerd terwijl de beschrijving is Bodemkundige boormonsteranalyse. Catalogus van 31 oktober 2019, misschien oude versie.

## Samenvatting
Figuur is denk ik gekopieerd uit SFR

## Beschrijving
De naam wandmonsteranalyse is verwarrend om dat verder overal gesproken wordt van boormonsteranalyse

## Oplossingsrichting
Vervang wandmonsteranalyse door boormonsteranalyse conform model en XSD

**Comment by BregjeBrugman** [comment]
is verbeterd in de 1.99 versie (25 okt. 2020)
