### ISSUE TITLE
AnalysesOperator in ...SampleAnalyses is bij BHR-P verplicht bij SFR optioneel

### ISSUE THREAD

**Issue by yke** [BROprogramma/booronderzoek#66]
## Type issue
Review sessie

## Waar
In BHR-P catalogus pagina 90 paragraaf 3.29.5. Zie SFR catalogus pagina 84 paragraaf 3.29.3

## Oplossingsrichting
Bij BHR-P ook optioneel maken

**Comment by BregjeBrugman** [comment]
30.5 uitvoerder analyse (attribuut van Boormonsteranalyse) kardinaliteit [0..1]

**Comment by BregjeBrugman** [comment]
kardinaliteit aangepast in werkafspraak tr. 3 (nr. 39), al verwerkt in stap 1
