### ISSUE TITLE
In de uitgifte is in de XSD het verkeerde type gerefereerd (boringToolType ipv boringToolTypeType)

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#67]
## Type issue
Implementatie 2.0

## Waar
uitgifte boodschappen xsd

## Samenvatting

In het complexType BoringToolTypeOverviewType 
moet bij het element boringToolType 
het type BoringToolTypeType zijn 
in plaats van BoringToolType.

## Oplossingsrichting
Reeds opgelost in de beschikbare xsd voor development.

**Comment by HanWelmer** [comment]
Dit was een fout, gemaakt bij het handmatig aanpassen van de bestaande XSD voor de uitgifteservice.
Bij de door imvertor gegenereerde XSD, op basis van het nu nog imcomplete logisch model, gaat het goed.
