### ISSUE TITLE
Omissie domein meetwaarde vormfactor Alfa

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#68]
## Type issue
omissie

## Waar
hoofdstuk 3.61, catalogus 1.99

## Samenvatting
Domein definitie ontbreekt.

# Oplossingsrichting
Moet zijn 'Meetwaarde 1.4'

**Comment by BregjeBrugman** [comment]
aangepast in werkafspraak tr. 3 (nr. 13)
