### ISSUE TITLE
Waterretentiewaarde#Bodemvochtpotentiaal heeft geen domein definitie, Waterretentiewaarde verdamping# bodemvochtpotentiaal verkeerd bereik

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#69]
## Type issue
Implementatie

## Waar
52.1

## Samenvatting
Domein definitie ontbreekt / incompleet / andersom

## Beschrijving

•	WaterRetentieWaarde#bodemvochtPotentiaal 
heeft geen domeindefinitie.  Echter het bereik is van -10e7 tot -0.1  (lijkt niet overeen te komen met de definitie elders)
•	Waterretentiewaarde verdamping# bodemvochtpotentiaal diepte 1 (t/m4)
heeft wel een definitie, maar hier lijkt het domein bereik andersom 0 tot -10e7 (niet klein naar groot)

## Oplossingsrichting
(Aanname) domein opbouw: opbouw ontbreekt, moet zijn 8.0 (conform de andere attributen bodemvochtpotentiaal, bereiken aanpassen.

**Comment by BregjeBrugman** [comment]
![image](https://user-images.githubusercontent.com/36854179/100745743-084eb980-33e0-11eb-9abf-6db24cf62235.png)

**Comment by BregjeBrugman** [comment]
![image](https://user-images.githubusercontent.com/36854179/100746072-857a2e80-33e0-11eb-906b-47fcac855f8a.png)

**Comment by BregjeBrugman** [comment]
aangepast in werkafspraak tr. 3 (nr. 40 en 41) al aangepast in stap 1
