### ISSUE TITLE
2.2 Registratieobject

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#7]
laatste alinea blz 11.

Er wordt voor objecten waarvan de gegevens in 1 keer worden vastgelegd als voorbeeld Sonderingen gegeven. Het zou duidelijk zijn om hier ook toe te lichten waaronder Booronderzoek valt.

**Comment by MarcelReuvers** [comment]
De suggestie is niet opgevolgd omdat het hier om een algemeen hoofdstuk gaat dat voor alle registratieobjecten dezelfde inhoud heeft.
