### ISSUE TITLE
XSD: ShrinkageDeterminationType#Temperature

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#70]
## Type issue
Implementatie

## Waar
Volgens catalogus, 3.44.4
![image](https://user-images.githubusercontent.com/6173283/98780857-be347280-23f5-11eb-974e-c797cce5755e.png)

## Samenvatting
Kardinaliteit 0..1
Mag geen waarde hebben 

## Oplossingsrichting
XSD aangepast (nillable attribuut)

**Comment by HanWelmer** [comment]
- Aangepast in BHR-P logisch model: tagged value voidable=Yes (was No) bij srcommon.ShrinkageDetermination.temperature.
- Aangepast in SFR logisch model: tagged value voidable=Yes (was No) bij srcommon.ShrinkageDetermination.temperature.
- srcommon.xsd in BHR-P in publieke GitHub aangepast.
- srcommon.xsd in SFR in publieke GitHub aangepast.

**Comment by yke** [comment]
Geldt dit alleen voor BHR-P of ook voor SFR. Shrinkage is een onderdeel van SRCommon.

**Comment by HanWelmer** [comment]
temperature nillable="true" geldt volgens de gegevenscatalogi voor SFR en BHR-P. Ik heb srcommon.xsd bij beide RO's in de publieke github aangepast.

**Comment by yke** [comment]
Ok

Omdat ze tot nu toe (en waarschijnlijk nog steeds zijn) gebruik ik slechts 1. Ook omdat Sjaak ooit aangegeven heeft dat op schemas.broservices.nl 1 srcommon zou komen.

Yke van Randen
Environmental Sciences Group
Wageningen University & Research
(Team Earth Informatics)
•     Postbus 47, 6700 AA, Wageningen
H     Wageningen Campus, Building 101 (Gaia), Kamer A 2.24  Droevendaalsesteeg 3, 6708 PB, Wageningen
•     +31 (0) 317 481828
Ê     +31 (0) 317 419000 (fax)
e•  mailto:yke.vanRanden@wur.nl
ü     http://www.earthinformatics.eu/
ü     https://www.wur.nl/en/Expertise-Services/Research-Institutes/Environmental-Research.htm
Available on Mo, Tu, We, Th.
