### ISSUE TITLE
XSD Entiteit Soil (Grond) per ongeluk verwijderd BhrCommon.xsd

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#71]
## Type issue
Implementatie

## Samenvatting
Vermoedelijk met het verwijderen van het attribuut grondsoort is ook de entiteit weggehaald.

## Oplossingsrichting
weer aangebracht

**Comment by HanWelmer** [comment]
Ik begrijp dit niet.

- De BHR-P catalogus versie 1.99 dd 25 maart 2020 bevat geen entiteit Grond. Zie [BHR-P Catalogus](https://www.bro-productomgeving.nl/bpo/latest/bodem-en-grondonderzoek/booronderzoek-bhr/bodemkundig-booronderzoek-bhr-p).
- bhrcommon.xsd in GitHub (branch master) bevat geen complexType met de name="SoilType". Dat komt overeen met de catalogus.
- EA conceptueel model bevat geen entiteit Grond. Dat komt overeen met de catalogus.
- EA logisch model bevat geen entiteit Soil. Dat komt overeen met de catalogus en het conceptueel model.

**Comment by HanWelmer** [comment]
Waarschijnlijk wordt bedoeld de gegevensgroep SoilType (Grondsoort).

- De BHR-P catalogus versie 1.99 dd 25 maart 2020 bevat een entiteit Grondsoort.
- EA conceptueel model bevat een entiteit Grondsoort (SoilType). Dat komt overeen met de catalogus.
- EA logisch model bevat een attributegrouptype SoilType (Grondsoort). Dat komt overeen met de catalogus en het conceptueel model.
- bhrcommon.xsd in GitHub (branch master) bevat een complexType SoilTypeType. Dat komt overeen met het logisch model.
- Er is (nog) geen BHR-P berichtencatalogus inname. Dus dat is (nog) geen probleem.
- De BHR-P berichtencatalogus uitgifte wordt hierdoor niet geraakt.

**Comment by HanWelmer** [comment]
Conclusie: probleem is opgelost.
