### ISSUE TITLE
XSD (ds_messages)

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#72]
## Type issue
implementatie

## Waar
[Geef aan over welke plek in het document de melding gaat. Bijvoorbeeld: 'Paragraaf x.x', 'pagina y'.]

## Samenvatting
Het aantal documenten (uitgifte) is van het type `integer` waar dat voor andere registratie-objecten `int` is. Het verschil is [hier ](https://stackoverflow.com/questions/15336872/xsd-what-is-the-difference-between-xsinteger-and-xsint) uitgelegd

## Beschrijving
Java genereert een `BigInteger` in plaats van een `Integer`

## Oplossingsrichting
vervang `integer` door `int`

**Comment by HanWelmer** [comment]
Alleen in de onderstaande gevallen wordt een xs:int gebruikt:

- gmw uitgifte numberOfDocuments xs:int
- cpt uitgifte numberOfDocuments xs:int
- bhr(-p) uitgifte numberOfDocuments xs:int
- epl uitgifte numberOfDocuments xs:int

In alle andere gevallen wordt een xs:integer gebruikt.

De uitzonderingen zijn oorspronkelijk met de hand gemaakte XSD-bestanden in tranche 1. Sinds tranche 2 worden dew XSD's gegenereerd door Imvertor.

Mijn voorstel is de huidige situatie te laten zoals die is. Dat wil zeggen de bovenstaande uitzonderingen omwille van backwardscompatibiliteit niet aanpassen aan de anderen. Met dien verstande dat EPL t.z.t. alsnog met een xs:integer zal worden gedaan, aangezien EPL in tranche 1 niet voldragen is geraakt en tijdens tranche 4 opnieuw opgepakt wordt.
