### ISSUE TITLE
Catalogus, BHR-P v1.99 BoorOnderzoek is afwezig in het overzicht van het domein model

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#73]
## Waar
Hoofdstuk 2

## Samenvatting
BoorOnderzoek is afwezig in het overzicht van het domein model

## Beschrijving
De boormosterbeschrijving / boormonsteranalyse is wel aanwezig

## Oplossingsrichting
Toevoegen?

**Comment by BregjeBrugman** [comment]
ja, moet opgenomen worden

**Comment by RuudMutsaers** [comment]
Is in de versie 2.09 van 1 juni verwerkt!
