### ISSUE TITLE
BHR-P Catalogus v1.99, hoofdstuk 2, laagcomponent, grondsoort onterecht aanwezig.

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#74]
## Type issue
Implementatie

## Waar
Hoofdstuk 2, laagcomponent, grondsoort

## Samenvatting
Het lijkt of er een oud plaatje is gebruikt. Grondsoort is entiteit alsmede attribuut. Dit lijkt me niet correct.

## Beschrijving
In hoofdstuk 3.22 lijkt het correct weergegeven.

## Oplossingsrichting
Gebruik actueel plaatje

**Comment by BregjeBrugman** [comment]
Grondsoort is entiteit. grondsoort als attribuut uit domeinmodel halen. (gegevensgroep niet zichtbaar maken)

**Comment by BregjeBrugman** [comment]
zie #64
