### ISSUE TITLE
XSD heeft elementen locatiespeciek catalogus ook alleen locatiespecifiek en diagram geen van beide. Lijkt SFR versie misschien ?

### ISSUE THREAD

**Issue by yke** [BROprogramma/booronderzoek#76]
## Type issue
Publieke consultatie

## Waar
Diagram in catalogus (20191031 catalogus Bodemkundige boormonsteranalyse 1-9) op p 12 bv entiteit 28, beschrijving op 93

## Samenvatting
Is dus niet in overeenstemming

**Comment by HanWelmer** [comment]
- Boormonsteranalyse in catalogus dd 25 maart 2020 bevat de attributen locatiespecifiek en onderzocht oppervlak. (zie https://www.bro-productomgeving.nl/bpo/latest/bodem-en-grondonderzoek/booronderzoek-bhr/bodemkundig-booronderzoek-bhr-p). Dat nemen we als uitgangspunt.
- Logisch model is goed. (svn revision = 4704).
- XSD is goed.
- Er is geen BHR-P Berichtencatalogus inname. Dus daar valt niets aan te doen.
- Diagram in BHR-P Berichtencatalogus uitgifte is goed.
- Vertaallijst in BHR-P Berichtencatalogus uitgifte is goed.
- Technische documentatie was in principe goed, maar het diagram toonde de attributen in alfabetische volgorde. Diagram aangepast met stand van zaken uit het logisch model.
