### ISSUE TITLE
3.62.1 gemodelleerde verzadigde waterdoorlatendheid

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#77]
## Type issue
Implementatie

## Waar
domein onbekend

## Samenvatting
Domein waarde niet gespecificeerd.

## Oplossingsrichting
Aanname: waarde 5.1, zie bijv. 3.47.13

**Comment by BregjeBrugman** [comment]
zie ook https://github.com/BROprogramma/SFR/issues/70

**Comment by BregjeBrugman** [comment]
meetwaarde verandert in meetwaarden in machten in werkafspraak tranche 3 (nr. 21)
