### ISSUE TITLE
Grond.bodemkundige grondsoort (Soil.pedologicalSoilName) = kleiigeLeem waarde is niet correct: komt niet voor in de codelijst.

### ISSUE THREAD

**Issue by yke** [BROprogramma/booronderzoek#78]
## Type issue
Review sessie aanleveren bij bronhouderportaal levert melding

## Waar
Grond.bodemkundige grondsoort

## Samenvatting
In de mapping bij WENR kan de waarde kleiigeLeem gerealiseerd worden. Deze mapping is 100% overgenomen van BHR-P.  De waarde kleiigeLeem zit niet in de catalogus van SFR noch in die van BHR-P, echter toch zijn er zonder meer profielen geleverd met die waarde. Het lijkt of de catalogi ook wat deze codelijst betreft, incompleet zijn.

## Beschrijving
Zie samenvatting

## Oplossingsrichting
Neem kleiigeLeem op in de codelijst.

**Comment by BregjeBrugman** [comment]
Voor SFR is het issue opgelost in versie 1.99. Bij BHR-P (nog) niet.

**Comment by yke** [comment]
Ok maar deze is wel blokkerend, juist bij BHR-P omdat we bij oude data regelmatig te weinig info hebben om een betere aanduiding af te leiden.

**Comment by BregjeBrugman** [comment]
opgenomen in werkafspraak tranche 3 (nr. 3)
