### ISSUE TITLE
2.4 kwaliteitsregime

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#8]
blz 12 laatste alinea.

De transitieperiode voor het voldoen aan IMBRO zou 5 jaar kunnen zijn. Dat is een erg lange periode.  Verkorten tot 1 jaar moet mogelijk zijn. Bronhouders die "makkelijk" willen omgaan met de BRO, zullen altijd tot het laatste jaar wachten.

**Comment by MarcelReuvers** [comment]
De termijn van vijf jaar is weggehaald; de catalogus zegt niets over termijnen dat wordt geregeld in de  ministeriele regeling.
