### ISSUE TITLE
karakteristieken (characteristics) lijken niet compleet.

### ISSUE THREAD

**Issue by sjaakd** [BROprogramma/booronderzoek#80]
## Type issue
implementatie

## Waar
uitgifte XSD

## Samenvatting
-

## Beschrijving

criteria:
```xml
                    <element name="analysisReportPeriod" type="brocom:DatePeriodType" minOccurs="0" maxOccurs="1"/>
                    <element name="analysisType" type="bhrcom:AnalysisTypeType" minOccurs="0" maxOccurs="1"/>
                    <element name="characteristicModelled" type="brocom:IndicationYesNoEnumeration" minOccurs="0" maxOccurs="1"/>
```
kennen geen counterpart in de geraporteerde characteristics (karakteristieken)

## Oplossingsrichting
dit lijkt een omissie en out-of-sync met SFR, waar deze wel symmetrisch aanwezig zijn.

**Comment by HanWelmer** [comment]
In de [documentatie](https://wiki.gdnnet.nl/display/BSta/BHR_P+tranche+3+stap+4+Technisch+transactiemodel+voor+uitgifte) van het TO staat een opmerking m.b.t. onduidelijkheid over de gewenste inhoud.

Voorstel is om in overleg met de BRO-afnemers te kijken welke concrete wensen er zijn en zo nodig de kengegevens uit te breiden.

**Comment by BregjeBrugman** [comment]
opgenomen in jira: https://jira.gdnnet.nl/browse/BROSVO-1249
en daarom hier gesloten
