### ISSUE TITLE
2.5 Formele en materiële historie

### ISSUE THREAD

**Issue by harryvanmanen** [BROprogramma/booronderzoek#9]
De 3e alinea is zeer onduidelijk:

__Het begrip formele historie wordt gebruikt voor de veranderingen van eigenschappen van een object in de registratie zelf. De meeste van die veranderingen gaan terug op veranderingen in de werkelijkheid, en de formele historie geeft aan wanneer de veranderingen geregistreerd zijn. Veranderingen in de registratie die niet het gevolg zijn van een verandering in de werkelijkheid, hebben altijd te maken met correcties. Het kan bijvoorbeeld gebeuren dat een dataleverancier erachter komt dat er een onjuiste waarde was geregistreerd en dan levert hij een verbetering aan. Bij correctie wordt het betreffende gegeven in de BRO overschreven en is de oude waarde van het gegeven niet meer beschikbaar voor de afnemers._

==> bijvoorbeeld: wat is een verandering van eigenschap in de registratie? Geeft formele historie alleen een tijdstip aan van verandering? een voorbeeld kan verhelderend zijn.

**Comment by MarcelReuvers** [comment]
De tekst van paragraaf 2.5 is verbeterd.
